version: "2"

services:
### console
    console:
        ports:
           - "8080:8080"
        build:
            context: ./images/console
            args:
                # console 容器 www-data用户密码
                - USERPASS=123456
        volumes_from:
            - php-fpm
            - nginx
            - mysql
            - redis
        volumes:
            - ./ssh:/home/www-data/.ssh
        links:
            - mysql
            - redis
        tty: true

### php-fpm
    php-fpm:
        build: ./images/php-fpm
        volumes:
            - ../:/var/www/
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"

### nginx
    nginx:
        build:
            context: ./images/nginx
            args:
                - PHP_UPSTREAM=web_php-fpm_1
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - php-fpm
        volumes:
            - ./logs/nginx/:/var/log/nginx/
            - ./images/nginx/sites:/etc/nginx/sites-available/
            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./ssh:/etc/nginx/cert

### mysql
    mysql:
        image: mysql:8.0.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        volumes:
            - ./data/mysql:/var/lib/mysql

### redis
    redis:
        image: redis:3.0.7
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
